package com.lessonfoundry.audit;

public enum AuditAction {
    LOGIN,
    LOGOUT,
    SOURCE_UPLOADED,
    SOURCE_UPDATED,
    SOURCE_DELETED,
    PACK_CREATED,
    PACK_GENERATED,
    ASSET_REGENERATED,
    ASSET_APPROVED,
    ASSET_REVISION_REQUESTED,
    PACK_PUBLISHED,
    USER_ROLE_CHANGED,
    USER_STATUS_CHANGED,
    USER_REGISTERED,
    USER_DELETED
}

